<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6b2ca1c0-bc7c-4b37-bcd1-2a8e4ebb8fac</testSuiteGuid>
   <testCaseLink>
      <guid>aa48ebc9-105b-460e-8b7e-f128f5faa664</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_SignUp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf2f9536-b70d-4e05-aba3-023ecef9d43f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aedb27c9-4753-464a-a4de-d012973d0398</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1e898a-9ff9-4a2b-a8e5-9bc53ab9ded8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3721faab-876f-4d14-9384-19f80da22d4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>009484d8-12e1-4f23-9e37-8bd5ff9fbe6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85849754-0f81-4142-a34b-41b8e858be5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e0cf195-e41e-42cb-876c-b064ea485858</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_SignIn</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84372f73-45cf-4651-989c-94f6a9a64fb7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataCSV</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>84372f73-45cf-4651-989c-94f6a9a64fb7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>9ddd80c0-a11f-4bcc-a6b3-9815cf676fc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84372f73-45cf-4651-989c-94f6a9a64fb7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Pwd</value>
         <variableId>9b997c30-8a85-4821-b6c3-36175ff050be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
